import { groupByDay, RAIL_GLYPHS, PIPELINE, CLOSED_STATUSES, type OverviewData, type SystemStatus, type AttentionItem, type campaignWorkspace, type CommandActivity, type researchWorkspace } from "./commandCenter.js";
import { OUTCOME_LABELS, type ResearchOutcome } from "../research/researcher.js";
import { STATUS_LABELS } from "../prospectStatus.js";
import { MODE_LABELS } from "./sendingState.js";
import { providerKnowledgeText } from "./shell.js";
import { appPage } from "./views.js";
import { card, MIN_COMPARE, emptyState, esc, fmtDate, funnelBar, icon, meter, options, pageHead, unavailable } from "./ui.js";

// Presentation of the existing read-only projections; no operational decisions here.
const state = (label: string, tone = "unknown") => `<span class="obs obs-${tone}">${esc(label)}</span>`;
const cardHead = (title: string, description: string, href?: string, action = "View all") => `<div class="card-head"><div><h2>${esc(title)}</h2><p>${esc(description)}</p></div>${href ? `<a href="${esc(href)}">${esc(action)} &rarr;</a>` : ""}</div>`;

export function activityFeed(rows: CommandActivity, limit = 12, now = new Date(), polished = false): string {
  if (!rows.length) return emptyState("No recorded activity yet.", "Discovery, research, outreach and product events appear here as work happens.");
  if (polished) {
    const highlighted = new Set(["Reply received", "Reply classified", "Message failed", "Message bounced", "Opt-out recorded", "Spam complaint recorded", "Analysis completed", "Prospect moved to qualified", "Prospect moved to ready to contact"]);
    return groupByDay(rows.slice(0, limit), now).map(g => `<div class="feed-day"><h3 class="feed-day-h">${esc(g.label)} <span>UTC</span></h3><ol class="feed">${g.events.map(e => `<li class="${highlighted.has(e.label) ? "event-key" : "event-routine"}"><span class="feed-glyph" aria-hidden="true">${highlighted.has(e.label) ? icon(e.kind === "outreach" ? "messages" : e.kind) : '<span class="event-dot"></span>'}</span><div><a href="${esc(e.href)}">${esc(e.label)}</a>${highlighted.has(e.label) ? `<p>${esc(e.name ?? "Unnamed business")}${e.internal ? " &middot; Internal test" : ""}</p>` : `<span class="event-business"> &middot; ${esc(e.name ?? "Unnamed business")}${e.internal ? " &middot; Internal test" : ""}</span>`}</div><time datetime="${e.at.toISOString()}" title="${fmtDate(e.at)}">${e.at.toISOString().slice(11, 16)}</time></li>`).join("")}</ol></div>`).join("");
  }
  return groupByDay(rows.slice(0, limit), now).map(g => `<div class="feed-day"><h3 class="feed-day-h">${esc(g.label)} &middot; UTC</h3><ol class="feed">${g.events.map(e => `<li><span class="feed-glyph">${icon(e.kind === "outreach" ? "messages" : e.kind)}</span><div><a href="${esc(e.href)}">${esc(e.label)}</a><p>${esc(e.name ?? "Unnamed business")}${e.internal ? " &middot; Internal test" : ""}</p></div><time datetime="${e.at.toISOString()}" title="${fmtDate(e.at)}">${e.at.toISOString().slice(11, 16)}</time></li>`).join("")}</ol></div>`).join("");
}

const railEvidence = (evidence: string) => evidence
  .replace("Sending isn't armed for this deployment (OUTREACH_SENDING_ENABLED=1).", "Sending is not armed.")
  .replace(/^1 candidates wait;/, "1 candidate waits;");

export function statusRail(d: SystemStatus, polished = false): string {
  if (polished) return `<section class="rail" aria-labelledby="system-rail-h"><header class="rail-head"><div><h2 id="system-rail-h">System status</h2><p>Checked here, or reported from recorded activity.</p></div><a href="/admin/system">Open Health &rarr;</a></header><ul class="rail-list">${d.rail.map(c => `<li class="s-${c.state}"><a class="rail-cell" href="${esc(c.href)}" title="${esc(c.evidence)}"><span class="rail-name">${esc(c.name)}</span><span class="rail-state"><span class="dot" aria-hidden="true">${RAIL_GLYPHS[c.state]}</span>${esc(c.label)}</span>${c.state === "attention" || c.state === "down" ? `<span class="rail-ev">${esc(railEvidence(c.evidence))}</span>` : ""}</a></li>`).join("")}</ul><details class="ov-context rail-context"><summary>Evidence &amp; timestamps</summary><dl>${d.rail.map(c => `<div><dt>${esc(c.name)} <span>${esc(c.label)}</span></dt><dd>${esc(c.evidence)}</dd></div>`).join("")}</dl></details></section>`;
  return `<section class="rail" aria-label="System status"><ul class="rail-list">${d.rail.map(c => `<li class="s-${c.state}"><a class="rail-cell" href="${esc(c.href)}"><span class="rail-name">${esc(c.name)}</span><span class="rail-state"><span aria-hidden="true">${RAIL_GLYPHS[c.state]}</span>${esc(c.label)}</span><span class="rail-ev">${esc(c.evidence)}</span></a></li>`).join("")}</ul></section>`;
}

export function sendingGuardrail(d: SystemStatus, polished = false): string {
  const s = d.sending;
  if (!s) return card("Sending guardrail", unavailable("Sending status"), { id: "guard-h", level: 2 });
  const { facts: f, verdict: v } = s;
  if (polished) return `<section class="guard m-${v.mode}" aria-labelledby="guard-h"><div><p class="eyebrow" id="guard-h">Sending guardrail</p><div class="guard-title"><span class="switch" aria-hidden="true"></span><strong>SENDING <b>${MODE_LABELS[v.mode]}</b></strong></div><p class="guard-detail">${v.mode === "off" ? "Nothing will be sent while sending is off." : esc(v.status.detail)}</p>${s.provider.kind === "unchecked" ? '<p class="guard-why">Gmail authorization has not been verified here. Check Sending.</p>' : ""}</div><dl class="guard-facts"><div><dt>Queue</dt><dd><b>${f.queued}</b><span>waiting</span></dd></div><div><dt>Capacity</dt><dd><b>${f.capacity.remaining} / ${f.capacity.limit}</b>${meter(f.capacity.used, f.capacity.limit)}<span>remaining &middot; rolling 24h</span></dd></div><div${f.stuck.length ? ' class="is-alert"' : ""}><dt>Unresolved</dt><dd><b>${f.stuck.length}</b><span>unknown outcomes</span></dd></div></dl><div class="guard-act"><a class="btn btn-secondary" href="/admin/outreach">Review Sending</a><span class="guard-last">Last send<br>${fmtDate(f.attention.lastSentAt)}</span></div><details class="ov-context guard-context"><summary>Sending context</summary><p>${esc(v.status.detail)} Provider: ${esc(providerKnowledgeText(s.provider))}. Counts include internal test operations.</p></details></section>`;
  return `<section class="guard m-${v.mode}" aria-labelledby="guard-h"><div><p class="eyebrow" id="guard-h">Sending guardrail</p><div class="guard-title"><span class="switch" aria-hidden="true"></span><strong>SENDING <b>${MODE_LABELS[v.mode]}</b></strong></div><p class="guard-detail">${esc(v.status.detail)}</p><p class="guard-why">Provider: ${esc(providerKnowledgeText(s.provider))}. Counts include internal test operations.</p></div><dl class="guard-facts"><div><dt>Queue</dt><dd><b>${f.queued}</b><span>waiting records</span></dd></div><div><dt>Capacity</dt><dd><b>${f.capacity.remaining} / ${f.capacity.limit}</b>${meter(f.capacity.used, f.capacity.limit)}<span>remaining &middot; rolling 24h</span></dd></div><div${f.stuck.length ? ' class="is-alert"' : ""}><dt>Unresolved</dt><dd><b>${f.stuck.length}</b><span>unknown outcomes</span></dd></div><div><dt>Last send</dt><dd><span>${fmtDate(f.attention.lastSentAt)}</span></dd></div></dl><div class="guard-act"><a class="btn btn-secondary" href="/admin/outreach">Review Sending</a><span class="small muted">Select &rarr; Review &rarr; Prepare</span></div></section>`;
}

function attentionSummary(i: AttentionItem): string {
  // Presentation only. Safety warnings keep their complete explanation visible.
  if (i.tier === 1) return i.why;
  const brief: Record<string, string> = {
    replies: "Review each reply. Honour opt-outs promptly.",
    approve: "Review the evidence before adding these as New prospects.",
    verify: "Verify the recorded evidence before making a decision.",
    eligible: "Eligible for a first message. Preparing creates drafts only.",
    drafts: "Review each email before queueing it.",
    refused: "The provider refused these messages. They were not sent.",
    signals: "Recent invitation engagement. Review before following up.",
  };
  return brief[i.key] ?? i.why;
}

function attentionRow(i: AttentionItem): string {
  const brief = attentionSummary(i);
  return `<li class="att-item t-${i.tone}"><span class="att-n">${i.count}</span><div class="att-copy"><h3 class="att-title">${esc(i.title)}</h3><p class="att-why">${esc(brief)}</p>${brief !== i.why ? `<details class="ov-context att-context"><summary>Context</summary><p>${esc(i.why)}</p></details>` : ""}</div><span class="att-age">${i.age ? `${i.age.kind === "oldest" ? "Oldest" : "Latest"}<br><b>${esc(i.age.text)}</b>` : '<span title="This age is not recorded">Age unavailable</span>'}</span><a class="btn btn-secondary btn-sm" href="${esc(i.href)}">${esc(i.action)}</a></li>`;
}

function needsMe(d: OverviewData): string {
  const gaps = d.attentionGaps.length ? `<p class="unavailable" role="status">Attention may be incomplete: ${esc(d.attentionGaps.join(", "))} unavailable.</p>` : "";
  const clear = `<div class="all-clear"><span class="all-clear-mark" aria-hidden="true">&#10003;</span><h3>ALL CLEAR</h3><p>No recorded decisions are waiting. Start with one collision/body shop and establish its sourced evidence.</p><a class="btn btn-secondary" href="/admin/discovery">Open Discovery</a></div>`;
  const tiers = [{ tier: 1, label: "Safety first" }, { tier: 2, label: "Inbound" }, { tier: 3, label: "Pipeline decisions" }, { tier: 4, label: "Outreach work" }, { tier: 5, label: "Engagement signals" }];
  const work = tiers.map(t => {
    const items = d.attention.filter(i => i.tier === t.tier);
    return items.length ? `<div class="att-tier"><h3 class="att-tier-h">${t.label}</h3><ol class="att-list">${items.map(attentionRow).join("")}</ol></div>` : "";
  }).join("");
  return card("What needs me", gaps + (d.attention.length ? work : d.attentionGaps.length ? "" : clear) + '<p class="att-footnote">Operational work includes internal tests.</p>', { id: "attention-h", level: 2, cls: "work-queue", sub: "Your work queue, in priority order." });
}

function nextAction(d: OverviewData): string {
  const i = d.attention[0];
  const missing = d.attentionGaps.length > 0;
  const title = missing ? "Verify the unavailable sources" : i?.title ?? "Research one collision/body shop";
  const why = missing ? "Some attention sources did not load. Resolve that uncertainty before relying on this overview." : i?.why ?? "Legitimate sourced collision evidence comes before qualification and outreach.";
  const href = missing ? "/admin/outreach" : i?.href ?? "/admin/discovery";
  return `<section class="card lv2 nba" aria-labelledby="next-h"><p class="nba-eyebrow">Next best action</p><p class="nba-intro">Start here</p><h2 class="nba-title" id="next-h">${esc(title)}</h2><p class="nba-what">${missing ? "Check the sources marked unavailable." : i ? `${i.count} ${i.count === 1 ? "item" : "items"} waiting.` : "Choose one business to understand."}</p><dl><div><dt>Why this next</dt><dd>${esc(why)}</dd></div><div class="nba-where"><dt>Where</dt><dd>${missing ? "Sending and the unavailable sections" : esc(i?.where ?? "Discovery")}</dd></div></dl><a class="btn" href="${esc(href)}">${missing ? "Review Sending" : esc(i?.action ?? "Open Discovery")} &rarr;</a></section>`;
}

function acquisition(d: OverviewData): string {
  if (!d.funnel.ok) return card("Acquisition funnel", unavailable("Acquisition funnel"), { id: "acquisition-h" });
  const f = d.funnel.value, o = f.outreach;
  const stages = PIPELINE.map(s => ({ label: STATUS_LABELS[s], n: f.everReached(s), base: null }));
  const reached = [{ label: "Emailed prospects", n: o.prospectsEmailed, base: null }, { label: "Reached prospects", n: o.prospectsReached, base: o.prospectsEmailed, baseLabel: "emailed" }, { label: "Replying prospects", n: o.replyingProspects, base: o.prospectsEmailed, baseLabel: "emailed" }];
  const invitations = [{ label: "Invitations sent", n: o.invitationsSent, base: null }, { label: "Invitations opened", n: o.opened, base: o.invitationsSent, baseLabel: "sent invitations" }, { label: "Analysis activated", n: o.activated, base: o.invitationsSent, baseLabel: "sent invitations" }];
  const inventory = PIPELINE.map(s => `<li><a class="inv-l" href="/admin/prospects?status=${s}">${esc(STATUS_LABELS[s])}</a><b class="inv-n">${f.inventory[s] ?? 0}</b></li>`).join("");
  const full = `<div class="fn-cols"><div><div class="fn-seg"><h3 class="fn-h">Ever reached <span>All time &middot; business prospects</span></h3><p class="fn-explain">Actual current or historical status records. No intermediate stage is inferred, and these are not one cohort.</p>${funnelBar(stages, "Recorded prospect progression")}<p class="card-note">Stage rates are omitted: status history may skip stages.</p></div><div class="fn-seg"><h3 class="fn-seg-h">Outreach reach</h3>${funnelBar(reached, "Business outreach reach")}</div><div class="fn-seg"><h3 class="fn-seg-h">Invitation engagement</h3>${funnelBar(invitations, "Sent invitation engagement")}</div></div><div class="fn-now"><h3 class="fn-h">Current inventory <span>Right now</span></h3><p class="fn-explain">Current states, separate from historical progression.</p><ul class="inv"><li class="inv-cand"><span class="inv-l">Candidates in review</span><b class="inv-n">${d.candidatesInReview ?? "&mdash;"}</b></li>${inventory}</ul><p class="inv-closed">${CLOSED_STATUSES.map(s => `${esc(STATUS_LABELS[s])}: ${f.inventory[s] ?? 0}`).join(" &middot; ")}</p><p class="card-note">Discovery records: ${f.candidates}. Approved candidates: ${f.approved}. Candidate counts and prospect counts have different denominators.</p></div></div>`;
  const current = [
    { label: "Candidates in review", n: d.candidatesInReview, href: "/admin/discovery" },
    { label: "Qualified", n: f.inventory.qualified ?? 0, href: "/admin/prospects?status=qualified" },
    { label: "Ready to contact", n: f.inventory.ready_to_contact ?? 0, href: "/admin/prospects?status=ready_to_contact" },
  ];
  return card("Acquisition funnel", `<div class="acq-summary"><div class="acq-current"><h3 class="fn-h">Current pipeline</h3><dl>${current.map(c => `<div><dt><a href="${c.href}">${esc(c.label)}</a></dt><dd>${c.n ?? "&mdash;"}</dd></div>`).join("")}</dl></div><div class="acq-performance"><h3 class="fn-h">Business outreach <span>All time &middot; ever reached</span></h3><div class="compact-bars">${funnelBar(reached.map(r => ({ ...r, base: null })), "All-time business outreach")}</div><p class="card-note">${o.prospectsEmailed < MIN_COMPARE ? "Too few to compare. Counts only." : "Distinct business prospects; detailed rates below."}</p></div></div><div class="acq-engagement"><span>Sent invitations</span><span><b>${o.opened} / ${o.invitationsSent}</b> opened</span><span><b>${o.activated} / ${o.invitationsSent}</b> activated</span></div><details class="ov-context acquisition-context"><summary>Full acquisition picture</summary>${full}</details>`, { id: "acquisition-h", sub: "Pipeline now. Business results over time.", link: { href: "/admin/analytics", label: "Open Funnel" } });
}

function product(d: OverviewData): string {
  if (!d.product.ok) return card("Product funnel", unavailable("Product activity"), { id: "product-h" });
  const p = d.product.value;
  const rows = [{ label: "Visitors", n: p.uniqueVisitors, base: null }, { label: "Uploads", n: p.uploadSessions, base: p.uniqueVisitors, baseLabel: "visitors" }, { label: "Analyses", n: p.realScanSessions, base: p.uniqueVisitors, baseLabel: "visitors" }, { label: "Exports", n: p.realExportSessions, base: p.realScanSessions, baseLabel: "analysing visitors" }, { label: "Contact clicks", n: p.contactClickSessions, base: p.uniqueVisitors, baseLabel: "visitors" }];
  return card("Product funnel", `<div class="compact-bars">${funnelBar(rows.map(r => ({ ...r, base: null })), "Observed product engagement")}</div><p class="card-note">All-time sessions &middot; real activity &middot; internal tests excluded.</p><details class="ov-context"><summary>Session details &amp; comparisons</summary>${funnelBar(rows, "Product session comparisons")}<p class="card-note">All-time distinct sessions, including direct visitors. Internal tests and sample activity excluded from real events. Stages may occur in different sessions; shares describe observed counts, not a guaranteed sequence. Too few to compare below 20 observations.</p></details>`, { id: "product-h", sub: "Are businesses using ReclaimBay?" });
}

function week(d: OverviewData): string {
  if (!d.week.ok) return card("Outreach snapshot", unavailable("Last seven days"), { id: "week-h" });
  const w = d.week.value;
  return card("Outreach snapshot", `<dl class="figs">${[["Sent messages", w.sent], ["Individual replies", w.replies], ["Opt-out events", w.optOuts], ["Provider refusals", w.failed], ["Invitations opened", w.opened], ["Analyses activated", w.activated]].map(([label, n]) => `<div><dt>${esc(label)}</dt><dd>${n}</dd></div>`).join("")}</dl><p class="card-note">Real business activity &middot; internal tests excluded.</p><details class="ov-context"><summary>What these counts mean</summary><p>Each metric uses its recorded event time. Opens are invitation opens, not email tracking. The window begins ${fmtDate(w.since)}.</p></details>`, { id: "week-h", sub: "Last 7 days", link: { href: "/admin/outreach/messages", label: "Messages" } });
}

export function overviewPage(d: OverviewData): string {
  const mode = d.system.sending?.verdict.mode;
  const count = d.attention.reduce((n, i) => n + i.count, 0);
  const issues = d.system.rail.filter(c => c.state === "down" || c.state === "attention").length;
  const unknown = d.system.rail.some(c => c.state === "unknown") || d.attentionGaps.length;
  const verdict = issues ? `${issues} system ${issues === 1 ? "check needs" : "checks need"} attention` : unknown ? "Some worker health is not observable" : "No observed system problems";
  return appPage("Acquisition Command Center - ReclaimBay", "overview", `<div class="ov-page ov-stack"><header class="ov-head"><div><h1>Acquisition Command Center</h1><p class="ov-verdict"><span class="v-send m-${mode ?? "unknown"}">${mode ? `Sending ${MODE_LABELS[mode]}` : "Sending unavailable"}</span><span class="vsep" aria-hidden="true">&middot;</span><span>${count} ${count === 1 ? "item needs" : "items need"} you</span><span class="vsep" aria-hidden="true">&middot;</span><span${issues ? ` class="${d.system.rail.some(c => c.state === 'down') ? 'v-bad' : 'v-attention'}"` : ""}>${esc(verdict)}</span></p><p class="ov-meta">Updated ${fmtDate(d.at)} &middot; refresh for the latest state.</p></div></header>${sendingGuardrail(d.system, true)}<div class="ov-grid"><div>${needsMe(d)}</div><aside class="ov-side" aria-label="Next action">${nextAction(d)}</aside></div>${statusRail(d.system, true)}${acquisition(d)}<div class="ov-pair">${week(d)}${product(d)}</div>${card("Recent activity", d.activity.ok ? activityFeed(d.activity.value, 10, d.at, true) : unavailable("Recorded activity"), { id: "recent-h", sub: "What happened while you were away.", link: { href: "/admin/activity", label: "Open Activity" } })}</div>`);
}

export function systemPage(d: SystemStatus): string {
  const s = d.sending;
  const problems = d.rail.filter(c => c.state === "attention" || c.state === "down");
  const unknown = d.rail.filter(c => c.state === "unknown");
  const services = (cells: SystemStatus["rail"]) => cells.map(c => `<article class="service-card s-${c.state}"><header><h3>${esc(c.name)}</h3><span class="service-state"><span class="dot" aria-hidden="true">${RAIL_GLYPHS[c.state]}</span>${esc(c.label)}</span></header><p>${esc(c.evidence)}</p>${c.state === "verified" ? "" : `<a href="${esc(c.href)}">Inspect ${esc(c.name)} &rarr;</a>`}</article>`).join("");
  const group = (id: string, title: string, hint: string, cells: SystemStatus["rail"]) => cells.length ? `<section class="health-group" aria-labelledby="${id}"><header><h2 id="${id}">${title}</h2><p>${hint}</p></header><div class="service-grid">${services(cells)}</div></section>` : "";
  return appPage("System health - ReclaimBay", "health", `${pageHead({ title: "System health", lede: "Verified responses and recorded worker activity.", actions: '<a class="btn btn-secondary" href="/admin/activity">Inspect activity</a>' })}
<div class="health-verdict${problems.length ? " has-issues" : ""}"><b>${problems.length ? `${problems.length} system ${problems.length === 1 ? "check needs" : "checks need"} attention` : unknown.length ? "Some system health is not verified" : "No observed system problems"}</b><span>${unknown.length} ${unknown.length === 1 ? "component has" : "components have"} unknown health. Activity records do not verify deployment health.</span></div>
<p class="health-checked">Checked ${fmtDate(d.at)} &middot; refresh for current evidence.</p>
${group("health-attention", "Needs attention", "Inspect the recorded evidence before taking action.", problems)}
${group("health-unknown", "Not verified here", "Missing observability is not a passing check.", unknown)}
${group("health-verified", "Verified by this request", "These responses were checked directly; worker deployment health remains separate.", d.rail.filter(c => c.state === "verified"))}
${group("health-recorded", "Other recorded states", "Activity and configuration only. These are not live worker checks.", d.rail.filter(c => c.state === "recent" || c.state === "off"))}
<div class="ov-page health-guard">${sendingGuardrail(d, true)}</div>
<div class="grid-2 section">${card("Sending readiness", s ? (s.verdict.blockers.length ? `<ul class="readiness-list">${s.verdict.blockers.map(x => `<li>${esc(x)}</li>`).join("")}</ul>` : '<p>Configuration checks passed. Provider verification is shown separately above.</p>') : unavailable("Sending readiness"), { id: "readiness-h", sub: "Existing safety checks" })}${card("Monitoring coverage", '<dl class="coverage-list"><div><dt>Checked by this request</dt><dd>Web and database responses.</dd></div><div><dt>Recorded activity</dt><dd>Worker records are evidence of activity, not deployment health.</dd></div><div><dt>External infrastructure</dt><dd>No Railway API is called. Deployment revision and process uptime are not verified here.</dd></div></dl>', { id: "coverage-h" })}</div>`);
}

export function activityPage(rows: CommandActivity, includeInternal: boolean): string {
  const kinds = { outreach: "Outreach", prospects: "Prospect", discovery: "Discovery", research: "Research", product: "Product" };
  const trail = rows.length ? groupByDay(rows.slice(0, 50), new Date()).map(g => `<section class="audit-day" aria-label="${g.events[0]!.at.toISOString().slice(0, 10)} UTC"><h3>${esc(g.label)}<span>${g.label === "Today" || g.label === "Yesterday" ? `${g.events[0]!.at.toISOString().slice(0, 10)} &middot; ` : ""}UTC</span></h3><ol class="audit-events">${g.events.map(e => `<li${e.internal ? ' class="audit-internal"' : ""}><span class="audit-kind">${kinds[e.kind]}</span><div class="audit-record"><a href="${esc(e.href)}">${esc(e.label)}</a><p>${esc(e.name ?? "Unnamed business")}</p>${e.internal ? '<span class="audit-test">Internal test</span>' : ""}</div><time datetime="${e.at.toISOString()}" title="${esc(e.at.toISOString())}">${e.at.toISOString().slice(11, 19)}<span>UTC</span></time></li>`).join("")}</ol></section>`).join("") : emptyState("No recorded activity yet.", "Discovery, research, outreach and product events appear here as work happens.");
  return appPage("Activity · ReclaimBay", "activity", `${pageHead({ title: "Activity", lede: "What actually happened. No inferred events." })}<form class="activity-toolbar" method="get" action="/admin/activity"><div class="row"><label><input type="checkbox" name="internal" value="1"${includeInternal ? " checked" : ""}> Include internal test activity</label><button class="btn-secondary btn-sm" type="submit">Apply</button></div><span>${includeInternal ? "Internal tests are marked on each record" : "Internal tests excluded"}</span></form><section class="card activity-stream">${cardHead(includeInternal ? "Business & internal test activity" : "Recorded business activity", "Most recent 50 events across the recorded sources. Newest first; timestamps in UTC.")}${trail}</section><details class="workspace-context"><summary>About this record</summary><p>Only stored acquisition, outreach and product events appear here. Events are grouped by their recorded UTC day; adjacent entries do not imply a causal relationship. This is a recent view, not a complete audit export.</p></details>`);
}

export function researchPage(d: Awaited<ReturnType<typeof researchWorkspace>>): string {
  const badge = (s: string) => state(s === "queued" ? "Queued" : s === "running" ? "Running" : s === "failed" ? "Failed" : "Completed", s === "failed" ? "no" : s === "completed" ? "yes" : "unknown");
  return appPage("Research · ReclaimBay", "discovery", `${pageHead({ title: "Research", lede: "Evidence for a business decision. Observed facts, identity checks and conflicting sources stay distinct.", actions: '<a class="btn btn-secondary" href="/admin/discovery?view=research">Research queue</a>' })}<form class="card filters" method="get" action="/admin/research" role="search"><div class="filter-row"><div><label class="lbl" for="research-q">Business</label><input id="research-q" name="q" type="search" value="${esc(d.q)}" maxlength="100" placeholder="Find a research run"></div><div><label class="lbl" for="research-status">Run state</label><select id="research-status" name="status">${options([["", "All states"], ["queued", "Queued"], ["running", "Running"], ["completed", "Completed"], ["failed", "Failed"]], d.status)}</select></div><div class="filter-actions"><button type="submit">Apply filters</button><a class="btn btn-secondary" href="/admin/research">Reset</a></div></div></form><p class="result-line">Showing ${d.rows.length} of ${d.total} recorded research runs.</p>${d.rows.length ? `<div class="scroll"><table class="tbl cards"><caption class="sr-only">Research runs</caption><thead><tr><th scope="col">Business</th><th scope="col">State</th><th scope="col">Finding</th><th scope="col">Evidence</th><th scope="col">Updated</th><th scope="col">Review</th></tr></thead><tbody>${d.rows.map(r => `<tr><td><a class="name" href="/admin/discovery/candidates/${r.candidate.id}#research">${esc(r.candidate.businessName)}</a><div class="sub">${esc([r.candidate.city, r.candidate.state].filter(Boolean).join(", "))}</div></td><td data-label="State">${badge(r.status)}</td><td data-label="Finding">${esc(r.outcome ? OUTCOME_LABELS[r.outcome as ResearchOutcome] ?? r.outcome.replace(/_/g, " ") : "No finding yet")}${Array.isArray(r.warnings) && r.warnings.length ? `<div class="sub">${r.warnings.length} warning${r.warnings.length === 1 ? "" : "s"} · review sources</div>` : ""}</td><td data-label="Evidence">${r._count.facts} facts · ${r._count.sources} sources<div class="sub">${r.pagesFetched} pages read</div></td><td data-label="Updated">${fmtDate(r.finishedAt ?? r.heartbeatAt ?? r.queuedAt)}</td><td data-label="Review"><a class="btn btn-secondary" href="/admin/discovery/candidates/${r.candidate.id}#research">Review evidence</a></td></tr>`).join("")}</tbody></table></div>` : `<section class="cc-card">${emptyState("No research runs in this view.", "Start with a candidate's verified website. Research stays reviewable until you make the decision.", '<a class="btn btn-secondary" href="/admin/discovery">Open discovery</a>')}</section>`}`);
}

export function campaignsPage(d: Awaited<ReturnType<typeof campaignWorkspace>>): string {
  const campaigns = d.metrics.filter(x => x.campaign !== "all");
  const records = campaigns.map(c => {
    const followUpOnly = c.firstMessages === 0 && c.followUps > 0;
    const metric = (label: string, n: number | null) => `<div><dt>${label}</dt><dd>${n === null ? '<span class="muted" title="Not attributable to this campaign">&mdash;</span>' : n}</dd></div>`;
    return `<article class="card campaign-card">${cardHead(c.campaign, d.versions.filter(v => (v.campaign ?? "(none)") === c.campaign).map(v => v.template).join(" · "), `/admin/outreach/messages?campaign=${encodeURIComponent(c.campaign)}`, "Review messages")}
<div class="campaign-reach"><b>${followUpOnly ? "&mdash;" : c.prospectsEmailed}</b><span>business prospects emailed</span><span class="campaign-sample">${followUpOnly ? "Prospect attribution belongs to the first message." : c.prospectsEmailed < MIN_COMPARE ? "Too few to compare. Counts only." : "Recorded counts · no inferred performance"}</span></div>
<div class="campaign-observations"><section><h3>Message outcomes</h3><dl class="campaign-metrics">${metric("Sent messages", c.sent)}${metric("Replying messages", c.replied)}${metric("Opt-outs", c.unsubscribed)}</dl><p>Sent means handed to the provider. Replies and opt-outs count messages.</p></section><section><h3>Invitation engagement</h3><dl class="campaign-metrics">${metric("Invitations opened", followUpOnly ? null : c.opened)}${metric("Analyses activated", followUpOnly ? null : c.activated)}</dl><p>${followUpOnly ? "Not attributable to this follow-up campaign." : "Attributed to the first message. Invitation opens are not email opens."}</p></section></div>
${c.unclassified || c.refusedBeforeSending || c.bounced || c.failedAfterSending || c.complained ? `<div class="campaign-attention"><b>Review recorded outcomes</b><p>${[c.unclassified ? `Messages with unclassified replies: ${c.unclassified}` : "", c.refusedBeforeSending ? `${c.refusedBeforeSending} refused before sending` : "", c.bounced ? `${c.bounced} bounced` : "", c.failedAfterSending ? `${c.failedAfterSending} failed after sending` : "", c.complained ? `Spam complaints: ${c.complained}` : ""].filter(Boolean).join(" &middot; ")}</p><a href="/admin/outreach/messages?campaign=${encodeURIComponent(c.campaign)}">Inspect campaign messages &rarr;</a></div>` : ""}
<details class="workspace-context"><summary>Attribution &amp; definitions</summary><p>All time, business results only. Internal tests excluded. Follow-up campaigns receive only the attribution supported by the existing funnel. Invitation engagement belongs to the first message's campaign; a dash means not attributable, never zero. Invitation opens are not email opens. Campaigns have different observation windows; these counts are not a performance ranking.</p><a href="/admin/outreach#funnel">Full campaign funnel &rarr;</a></details></article>`;
  }).join("");
  return appPage("Campaigns · ReclaimBay", "campaigns", `${pageHead({ title: "Campaigns", lede: "Recorded outreach outcomes, grouped by the campaign stored on each message.", actions: '<a class="btn btn-secondary" href="/admin/outreach/messages">Open messages</a>' })}<p class="workspace-scope">All time &middot; business results &middot; internal tests excluded</p>${records ? `<div class="campaign-list">${records}</div>` : `<section class="card">${emptyState("Your first campaign starts with one message.", "Once a business draft is prepared, its stored campaign and email version appear here. No sending is enabled by visiting this workspace.", '<a class="btn btn-secondary" href="/admin/outreach/messages?view=eligible">Review eligible prospects</a>')}</section>`}<details class="workspace-context"><summary>What campaign reporting covers</summary><p>Campaigns currently group recorded messages; targeting and editable cohort management are not implemented. Delivery, email opens and recovered revenue are not inferred.</p></details>`);
}

export function diagnosticPage(): string {
  return appPage("Campaign diagnostic · ReclaimBay", "overview", `${pageHead({ title: "Campaign diagnostic", lede: "A reserved home for learning from real acquisition evidence." })}<section class="cc-card cc-placeholder"><span class="eyebrow">Planned workspace</span><h2>Useful conclusions need real observations.</h2><p>The diagnostic engine is not built. This space will separate observed data, interpretation, hypotheses and recommended experiments, rather than turning a small pilot into confident-looking predictions.</p><div class="cc-next"><b>What you can inspect today</b><p>Stored campaigns, message outcomes, individual replies, invitation activity and real product events.</p><a class="btn btn-secondary" href="/admin/campaigns">Explore recorded campaigns →</a></div></section>`);
}
